### ISSUE TITLE
Add valtimer warp teleport

### ISSUE THREAD

**Issue by agustinesco** [lambdaclass/mirra_backend#309]
The "dash" skill of valtimer will be a teleport to the destination instead of a dash

While the teleporting is occurring the player should not take damage

Implement the same for every dash and leap mechanic

**Comment by lotuuu** [comment]
What should happen if the player takes damage while teleporting?

**Comment by agustinesco** [comment]
> What should happen if the player takes damage while teleporting?

We decided that the player should not take damage while teleporting since you wont be able to see you in the animation, we talked about this with @marco-paulucci
