### ISSUE TITLE
[FEATURE] Data Tracking System

### ISSUE THREAD

**Issue by marco-paulucci** [lambdaclass/mirra_backend#525]
**NOTE: See bottom [comment](https://github.com/lambdaclass/mirra_backend/issues/525#issuecomment-2105145623)**

## 🚀 Feature

Depends on lambdaclass/curse_of_mirra#905

We need to implement tracking of various events that happen inside and outside matches. Various subsystems will eventually rely on this feature: daily/weekly quests, events, and in the future: challenges/achievements. 

For now, the primary goal should be to figure out a proper architecture for tracking this information, i.e. how will the data be structured and how are events going to be triggered through the code, in a way that is versatile and expandable. 

**Some example stats for a basic system:**
- Kills (also storing killer and killed classes, and skill that was used) (also save if the kill is against a bot or player)
- Deaths (see above parentheses)
- Damage dealt
- Damage received
- Heal
- Times the user placed 1st... all the way to 10th
- Match count (per class and total)
- Time spent inside the game app
- Time spent inside matches
- Win-streak (negative number for losses streak)
- Highest kill-streak (streaks reset at every game)
- Crate abilities used

**Future use cases:**
- Game currencies and skin shards
- More specific/arbitrary stats for achievements and challenges
- Derivated stats (win rate%, time in combat%, K/D ratio, etc)

**Comment by mgrunwaldt** [comment]
@marco-paulucci assigned this to you, not to implement it but to define what we need exactly. This is what we have in the notion:
<img width="426" alt="image" src="https://github.com/lambdaclass/mirra_backend/assets/22064054/2da89bfa-fe04-4b17-b14f-1431bb9604d2">

**Comment by AminArria** [comment]
This issue will be continued in #601

Current PR #578 will only address the setup to track game match data and some basic info like kill count, deaths, win/loss
