### ISSUE TITLE
[FEATURE] Json Configurator webApp

### ISSUE THREAD

**Issue by tvillegas98** [lambdaclass/mirra_backend#635]
We have to add a way to show, create or edit our json config files. We already have an app Configurator with Phoenix integrated that we can use as scaffolding. We should accomplish the following things:

- [ ] Display the config as key/value pairs. This can be in a tabular format similar to Excel or in another way.
- [ ] Use a relational model to store the data
- [ ] Differentiate between games (Champions and Curse).
- [ ] Enable real-time editing of the configs. This means that after making changes to the config and saving it, all new matches should use the updated config.
- [ ] Configurator app should have their own users that are not related to mirra's users.
Things to consider:
- In Curse of Mirra, we have all the config in a single file, we can consider it to split them all on different files. 
- Otherwise, Champions does have different config files. 
- We can have tabs/sections to edit these different files, this way could give us a more confortable way to look and change the configurations

**Comment by manucamejo** [comment]
We built a web configurator
