### ISSUE TITLE
[REFACTOR] Migrate missing config.json fields to configurator app

### ISSUE THREAD

**Issue by agustinesco** [lambdaclass/mirra_backend#852]
- [x] Power ups -> https://github.com/lambdaclass/mirra_backend/pull/853
- [x] Effects -> https://github.com/lambdaclass/mirra_backend/pull/856
- [x] Crates -> https://github.com/lambdaclass/mirra_backend/pull/854
- [x] Traps -> https://github.com/lambdaclass/mirra_backend/pull/860

**Comment by manucamejo** [comment]
done
