### ISSUE TITLE
[DOCS] Create script to setup a new server

### ISSUE THREAD

**Issue by manucamejo** [lambdaclass/mirra_backend#919]
Estimated time: 2hs

Create a document with:
- server requirements
- dependencies
- steps
- env vars
- ports to open
- etc.
Everything necessary to set up a server from scratch

**Comment by Nico-Sanchez** [comment]
https://www.notion.so/lambdaclass/How-to-set-up-a-new-Mirra-server-c88e0ebd99824a2abcda04b449e94033?pvs=4
