### ISSUE TITLE
[BUG] Kill counted twice

### ISSUE THREAD

**Issue by manucamejo** [lambdaclass/mirra_backend#922]
Estimated time: 5hs development + 2hs review 

We think that Tommy died then immediately got a power up, got healed, then got killed again. That bug is mentioned here -> https://github.com/orgs/lambdaclass/projects/22/views/1?filterQuery=&pane=issue&itemId=79465428

https://github.com/user-attachments/assets/bafa8b63-c323-4f37-a9d5-d9fc8e7b8149

**Comment by Nico-Sanchez** [comment]
Solved in https://github.com/lambdaclass/mirra_backend/pull/948
